# Nome da aplicação Spring Boot
spring.application.name=ninjas

# ==========================================
# Configurações de Conexão com o Banco de Dados
# ==========================================

# O endereço de conexão (URL) para o banco de dados PostgreSQL chamado 'ninjas'
spring.datasource.url=jdbc:postgresql://localhost:5432/ninjas

# O nome de usuário do administrador do banco de dados
spring.datasource.username=postgres

# A senha para acessar o banco de dados
spring.datasource.password=postdba

# Define explicitamente a classe do Driver JDBC do PostgreSQL que fará a ponte entre o Java e o banco
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# Configurações do JPA / Hibernate
# ==========================================

# Atualiza a estrutura das tabelas no banco de dados automaticamente com base nas classes @Entity do Java
spring.jpa.hibernate.ddl-auto=update

# Exibe no terminal (console) todas as consultas SQL geradas pelo Hibernate
spring.jpa.show-sql=true

# Quebra as linhas e indenta o SQL exibido no console, tornando as queries muito mais fáceis de ler
spring.jpa.properties.hibernate.format_sql=true

# Informa ao Hibernate qual "sotaque" do SQL ele deve usar (neste caso, as especificidades do PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

sever.pont = 8082